
# Simplified Transformer


In [17]:

import numpy as np

def relu(matrix):
    return np.maximum(0, matrix)

def leftmost_unique_hard_attention(matrix):
     
    n_rows, n_cols = matrix.shape
    attention = np.zeros_like(matrix)
    for row_idx in range(n_rows):
        row_scores = matrix[row_idx]
        max_score = np.max(row_scores)

        max_indices = np.where(row_scores == max_score)[0]
        
        if len(max_indices) > 0:
            # Select the left-most one
            selected_col = max_indices[0]
            attention[row_idx, selected_col] = 1
    
    return attention
    
# Define X0: abbc
X0 = np.array([[0,0,1],
              [0,1,0],
              [0,1,0],
              [1,0,0]])

# Define X0: bacb
X0 = np.array([[0,1,0],
              [0,0,1],
              [1,0,0],
              [0,1,0]])

# Define matrices Q, K, V, O
Q = np.array([[2, 0],
              [0, 2],
             [0, 0]])

K = np.array([[0, 0],
              [0, 2],
             [2, 0]])

V = np.array([[1, 0],
              [0, 0],
             [0, 1]])

O = np.array([[2, 2, 2],
              [3, 1, 0]])

result = (X0 @ Q) @ (X0 @ K).T
print(result)
A=leftmost_unique_hard_attention(result)
print(A)

#Calculate X1
X1 = relu( A @ X0 @ V @ O) + X0
print(X1) 

#threshold 
t=1
n_rows, n_cols = X1.shape
if X1[n_rows-1][0] >= t:
    print("True")
else:    
    print("False")

[[4 0 0 4]
 [0 0 0 0]
 [0 4 0 0]
 [4 0 0 4]]
[[1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]]
[[0 1 0]
 [0 0 1]
 [4 1 0]
 [0 1 0]]
False
